version: '3.8'
services:
  db:
    image: postgres
    container_name: realtrading-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=realtrading
  main-service:
    build:
      context: .
      dockerfile: main-service/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./main-service:/app
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@realtrading-db/realtrading?sslmode=disable
    depends_on:
      - db
  matching-service:
    build:
      context: .
      dockerfile: matching-service/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./matching-service:/app
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@realtrading-db/realtrading?sslmode=disable
    depends_on:
      - db

networks:
  fullstack:
    driver: bridge